import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
interface Lead{id:string;payload:{type:string;senderName:string;senderEmail:string;senderPhone:string;data:Record<string,unknown>};status:string;created_at:string}
interface Delivery{lead_id:string;kind:string;state:string;last_error?:string}
export default function Leads(){
  const [leads,setLeads]=useState<Lead[]|null>(null),[delivery,setDelivery]=useState<Delivery[]>([]),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[configured,setConfigured]=useState(false),[selected,setSelected]=useState<Lead|null>(null),[status,setStatus]=useState('qualified'),[reason,setReason]=useState('');
  const call=async(url:string,data?:unknown)=>{const r=await fetch(url,{credentials:'same-origin',...(data?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}:{})});const v=await r.json();if(!r.ok)throw new Error(v.error||'Request failed');return v;};
  const refresh=async()=>{const v=await call('/api/admin/leads');setLeads(v.leads);setDelivery(v.delivery);setConfigured(v.metaConfigured);};
  useEffect(()=>{void refresh().catch(()=>{});},[]);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
  const change=async(e:React.FormEvent)=>{e.preventDefault();await run(async()=>{await call('/api/admin/status',{id:selected?.id,status,reason});setSelected(null);setReason('');await refresh();});};
  const button='px-5 py-3 rounded-lg border border-zinc-600 disabled:opacity-50';
  return <main className="max-w-6xl mx-auto px-5 py-12"><Link to="/" className="text-zinc-400 text-sm">← Back to Zebra</Link><div className="flex flex-wrap justify-between gap-4 mt-8 mb-7"><h1 className="text-3xl font-bold">Zebra lead manager</h1>{leads&&<button className={button} onClick={()=>void run(async()=>{await call('/api/admin/logout',{});setLeads(null);setChallenge('');})}>Sign out</button>}</div>
  {message&&<p role="alert" className="p-4 mb-5 rounded-lg border border-amber-800 text-amber-200">{message}</p>}
  {!leads?<div className="max-w-md p-7 rounded-2xl border border-zinc-700 bg-zinc-900"><h2 className="text-xl font-bold mb-3">Staff sign-in</h2><p className="text-sm text-zinc-400 mb-6">A one-time code will be sent to the business notification email configured for this site.</p>{!challenge?<button disabled={busy} className={button} onClick={()=>void run(async()=>{const v=await call('/api/admin/request-code',{});setChallenge(v.challenge);})}>Send sign-in code</button>:<form onSubmit={e=>{e.preventDefault();void run(async()=>{await call('/api/admin/verify-code',{challenge,code});setCode('');await refresh();});}}><label className="block text-sm">Six-digit code<input value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" required className="block w-full p-3 my-3 border border-zinc-600 bg-black rounded-lg"/></label><button disabled={busy} className={button}>Sign in</button></form>}</div>:<>
    <div className="p-5 rounded-xl bg-zinc-900 border border-zinc-700 mb-6"><p className="font-semibold">{configured?'Meta server connection configured':'Meta server connection needs configuration'}</p><p className="text-sm text-zinc-400 mt-2">Qualify after confirming fit and buying intent. Disqualify only after review and record the reason. Sales lead outcomes for visitors who allowed advertising measurement are queued for Meta. Dealer and support statuses stay in this dashboard. A saved status is not proof of Meta delivery; check the delivery status below.</p><p className="text-sm text-zinc-400 mt-2">To review contacts inside Meta Leads Center, export the CSV and upload it there. The export includes only sales inquiries whose visitors allowed Meta measurement. Conversion events do not create Leads Center contact cards; status changes made there do not sync back to this dashboard.</p><div className="flex flex-wrap gap-3 mt-4"><a className={button} href="/api/admin/export">Export leads for Meta</a><a className={button} href="https://business.facebook.com/latest/leads_center?business_id=539125005489186&asset_id=448337188370724" target="_blank" rel="noopener noreferrer">Open Meta Leads Center</a><button className={button} disabled={busy} onClick={()=>void run(refresh)}>Refresh</button></div></div>
    <p className="text-sm text-zinc-400 mb-4">Showing up to 250 newest inquiries. Dealer and support inquiries are separate from sales lead events.</p>
    {!leads.length?<p className="py-10 text-zinc-400">New website inquiries will appear here.</p>:<div className="space-y-4">{leads.map(lead=><article key={lead.id} className="p-6 rounded-xl border border-zinc-700"><div className="flex justify-between gap-4 flex-wrap"><div><span className="text-xs uppercase tracking-widest text-primary">{lead.payload.type} · {lead.status}</span><h2 className="text-xl font-semibold mt-2">{lead.payload.senderName}</h2><p className="text-xs text-zinc-500 mt-1">{new Date(lead.created_at).toLocaleString()}</p></div><button className={button} onClick={()=>{setSelected(lead);setStatus(lead.status==='new'?'qualified':lead.status);setReason('');}}>Review status</button></div><div className="flex gap-5 flex-wrap text-sm mt-4"><a className="underline" href={`mailto:${lead.payload.senderEmail}`}>{lead.payload.senderEmail}</a><a className="underline" href={`tel:${lead.payload.senderPhone.replace(/[^+0-9]/g,'')}`}>{lead.payload.senderPhone}</a></div><dl className="grid sm:grid-cols-3 gap-4 mt-5 text-sm">{Object.entries(lead.payload.data).map(([k,v])=><div key={k}><dt className="text-zinc-500 capitalize">{k.replace(/([A-Z])/g,' $1')}</dt><dd className="break-words mt-1">{String(v)}</dd></div>)}</dl><p className="text-xs text-zinc-400 mt-5">{delivery.filter(d=>d.lead_id===lead.id).map(d=>`${d.kind}: ${d.state}${d.last_error?` (${d.last_error})`:''}`).join(' · ')}</p></article>)}</div>}
  </>}
  {selected&&<div className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-5"><form onSubmit={change} role="dialog" aria-modal="true" aria-label="Review lead status" className="w-full max-w-md p-7 bg-zinc-900 rounded-2xl border border-zinc-600"><h2 className="text-xl font-bold">Review {selected.payload.senderName}</h2><label className="block mt-5 text-sm">Status<select value={status} onChange={e=>setStatus(e.target.value)} className="block w-full mt-2 p-3 bg-black border border-zinc-600 rounded-lg"><option value="new">Needs review</option><option value="qualified">Qualified</option><option value="disqualified">Disqualified</option></select></label><label className="block mt-5 text-sm">Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={300} required className="block w-full mt-2 p-3 bg-black border border-zinc-600 rounded-lg" placeholder="For example: confirmed model, delivery area, and timing"/></label><div className="flex gap-3 mt-6"><button disabled={busy} className={button}>Save status</button><button type="button" className={button} onClick={()=>setSelected(null)}>Cancel</button></div></form></div>}
  </main>;
}
